# Numpy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
my_array = np.array(my_list)

In [4]:
my_array

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,11,2) #start end stepsize

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [18]:
np.eye(4)       #this is identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(5)

array([0.32915403, 0.6280555 , 0.22642775, 0.6859908 , 0.70372541])

In [22]:
np.random.rand(3,3)

array([[0.71896898, 0.09397363, 0.92724177],
       [0.70425657, 0.26892925, 0.53389649],
       [0.07613666, 0.34130656, 0.86602612]])

In [23]:
np.random.randn(2)

array([ 1.50553738, -0.87552315])

In [30]:
np.random.randint(1,10,5) #if want unique than use set

array([2, 1, 7, 4, 6])

In [32]:
ranarr = np.random.randint(0,50,10)

In [33]:
ranarr

array([ 2, 11,  4, 25,  0, 11, 35, 12, 48, 31])

In [37]:
arr = [1,2,3,4,5,7,6,8,9,10,11,12,15,1,3]
arr = np.array(arr)
arr.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 7,  6,  8,  9, 10],
       [11, 12, 15,  1,  3]])

In [38]:
ranarr.max()

48

In [39]:
ranarr.argmax()

8

In [40]:
ranarr.argmin()

4

In [41]:
arr = arr.reshape(3,5)

In [42]:
arr.shape

(3, 5)

In [43]:
arr.dtype

dtype('int64')

In [45]:
from numpy.random import randint

In [48]:
randint(2,10)

4